spring.application.name=bem-feito-api

# Banco de dados
spring.datasource.url=${DB_URL:jdbc:mysql://127.0.0.1:3306/bem_feito?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# Servidor
server.port=8080